# -*- coding: utf-8 -*-
"""Firesim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WmqS3xLWupVMM4OlvPyO55YRyTTnu72
"""

!pip install colorama

from colorama import Fore
import random

class Agent:
    def __init__(self, x, y):
        self.x = x
        self.y = y

class Feu(Agent):
    def __init__(self, x, y):
        super().__init__(x, y)
        self.symbole = "F"

class Pompier(Agent):
    """🔹 "Pompier Intelligent" : chasse le feu le plus proche et l'éteint."""
    def __init__(self, x, y):
        super().__init__(x, y)
        self.symbole = "P"
        self.eau = 10  # Réserve d'eau limitée

    def feu_le_plus_proche(self, liste_feux):
        """Retourne le feu le plus proche (distance de Manhattan)."""
        if not liste_feux:
            return None
        return min(liste_feux, key=lambda f: abs(f.x - self.x) + abs(f.y - self.y))

    def deplacer_vers(self, cible, grille, largeur, hauteur):
        """Se déplace d'une case vers la cible."""
        old_x, old_y = self.x, self.y
        dx = cible.x - self.x
        dy = cible.y - self.y

        if abs(dx) >= abs(dy):
            self.x += 1 if dx > 0 else -1
        else:
            self.y += 1 if dy > 0 else -1

        # Respecter les bords
        self.x = max(0, min(self.x, largeur - 1))
        self.y = max(0, min(self.y, hauteur - 1))

        grille[old_y][old_x] = None
        if grille[self.y][self.x] is None:
            grille[self.y][self.x] = self

    def eteindre(self, feu, grille):
        """Éteint un feu adjacent et consomme de l'eau."""
        grille[feu.y][feu.x] = None
        self.eau -= 1
        print(Fore.CYAN + f"  💧 Feu éteint en ({feu.x},{feu.y}) ! Eau restante : {self.eau}" + Fore.RESET)

class Environnement:
    def __init__(self, largeur, hauteur):
        self.largeur = largeur
        self.hauteur = hauteur
        self.grille = [[None for _ in range(largeur)] for _ in range(hauteur)]
        self.liste_feux = []
        self.pompier = None

    def initialiser(self, nb_feux):
        # Placer le pompier
        x = random.randint(0, self.largeur - 1)
        y = random.randint(0, self.hauteur - 1)
        self.pompier = Pompier(x, y)
        self.grille[y][x] = self.pompier

        # Placer les feux
        for _ in range(nb_feux):
            x = random.randint(0, self.largeur - 1)
            y = random.randint(0, self.hauteur - 1)
            while self.grille[y][x] is not None:
                x = random.randint(0, self.largeur - 1)
                y = random.randint(0, self.hauteur - 1)
            feu = Feu(x, y)
            self.liste_feux.append(feu)
            self.grille[y][x] = feu

    def afficher(self):
        for y in range(self.hauteur):
            for x in range(self.largeur):
                cell = self.grille[y][x]
                if cell is None:
                    print('.', end=' ')
                elif isinstance(cell, Pompier):
                    print(Fore.BLUE + 'P' + Fore.RESET, end=' ')
                elif isinstance(cell, Feu):
                    print(Fore.RED + 'F' + Fore.RESET, end=' ')
            print()

    def mettre_a_jour(self):
        p = self.pompier
        if p.eau <= 0:
            print(Fore.YELLOW + "Plus d'eau ! Le pompier est à sec." + Fore.RESET)
            return

        cible = p.feu_le_plus_proche(self.liste_feux)
        if cible is None:
            return

        dist = abs(cible.x - p.x) + abs(cible.y - p.y)

        if dist <= 1:
            # Adjacent : éteindre le feu
            p.eteindre(cible, self.grille)
            self.liste_feux.remove(cible)
            self.grille[p.y][p.x] = p
        else:
            # Se déplacer vers le feu
            p.deplacer_vers(cible, self.grille, self.largeur, self.hauteur)

        # 20% de chance qu'un nouveau feu apparaisse
        if random.random() < 0.20 and len(self.liste_feux) < 15:
            x = random.randint(0, self.largeur - 1)
            y = random.randint(0, self.hauteur - 1)
            if self.grille[y][x] is None:
                nouveau_feu = Feu(x, y)
                self.liste_feux.append(nouveau_feu)
                self.grille[y][x] = nouveau_feu
                print(Fore.RED + "  🔥 Nouveau feu !" + Fore.RESET)

# === Lancement ===
largeur, hauteur = 10, 10
nb_feux = 6
nb_tours = 40

env = Environnement(largeur, hauteur)
env.initialiser(nb_feux)

for tour in range(nb_tours):
    env.afficher()
    print(f"Tour {tour + 1}/{nb_tours} | Feux : {len(env.liste_feux)} | Eau : {env.pompier.eau}")
    env.mettre_a_jour()

    if len(env.liste_feux) == 0:
        print(Fore.GREEN + "\n✅ Tous les feux sont éteints !" + Fore.RESET)
        break
    if env.pompier.eau <= 0:
        print(Fore.RED + f"\n💧 Eau épuisée. {len(env.liste_feux)} feux restants." + Fore.RESET)
        break

env.afficher()